# Generated by Django 2.1 on 2018-08-31 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitationmodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='grouprequestmodel',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='groupinvitationmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='grouprequestmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
