# Generated by Django 2.1 on 2018-08-27 11:32

import database.models.group_media
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='media',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='meta',
        ),
        migrations.AlterField(
            model_name='groupmediamodel',
            name='cover_photo',
            field=models.ImageField(upload_to=database.models.group_media.get_upload_cover),
        ),
        migrations.AlterField(
            model_name='groupmediamodel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='database.GroupModel'),
        ),
        migrations.AlterField(
            model_name='groupmediamodel',
            name='logo',
            field=models.ImageField(upload_to=database.models.group_media.get_upload_logo),
        ),
        migrations.AlterField(
            model_name='groupmetamodel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='database.GroupModel'),
        ),
    ]
