# Generated by Django 2.1 on 2018-08-31 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180831_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmediamodel',
            old_name='cover_photo',
            new_name='cover',
        ),
    ]
