# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180825_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BoardModel'),
        ),
    ]
