# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 04:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180826_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
