# Generated by Django 2.1 on 2018-08-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20180826_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='database.BoardModel'),
        ),
    ]
