# Generated by Django 2.1 on 2018-08-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20180826_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='group',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.GroupModel'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BoardModel'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
