# Generated by Django 2.1 on 2018-10-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractformmodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='coachformmodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='trusteeformmodel',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='abstractformmodel',
            old_name='form_instantiatior',
            new_name='form_instantiator',
        ),
        migrations.AddField(
            model_name='abstractformmodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_forms.abstractformmodel_set+', to='contenttypes.ContentType'),
        ),
    ]
