# Generated by Django 2.1 on 2018-10-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamContractFormModel',
            fields=[
                ('abstractformmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.AbstractFormModel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('forms.abstractformmodel',),
        ),
    ]
