# Generated by Django 2.1 on 2018-10-10 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('form_text_content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CoachModel',
            new_name='CoachFormModel',
        ),
        migrations.RenameModel(
            old_name='TrusteeModel',
            new_name='TrusteeFormModel',
        ),
    ]
