# Generated by Django 2.1 on 2018-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_teamcontractformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcontractformmodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
